### ISSUE TITLE
Tests still fail when using TRYCMD=overwrite

### ISSUE THREAD

**Issue by SUPERCILEX** [assert-rs/trycmd#137] opened 2022-09-30 20:03 UTC
They shouldn't fail when overwriting, otherwise it makes it seem like overwriting failed. This is how [goldenfile](https://docs.rs/goldenfile/latest/goldenfile/) works.

**Comment by epage** [comment] 2022-09-30 20:17
This is a duplicate of https://github.com/assert-rs/trycmd/issues/31

**Closed by epage** 2022-09-30 20:17 UTC
